language: cpp
compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y libboost-system-dev
  - sudo apt-get install -y libboost-filesystem-dev
  - sudo apt-get install -y libboost-thread-dev
  - sudo apt-get install -y libboost-chrono-dev
  - sudo apt-get install -y libtbb-dev
  - mkdir build
  - cd build
  - cmake ..

script: make
