language: cpp
compiler:
  - clang

os:
   - linux

dist: trusty
sudo: required

env:
  global:
   - secure: "H4JJrrsbFcamFrlGBPLXHdKlkt9ufkN2jAxrZ6+hXLuf/AxoYp7tP1F7jWNiELrE5jauiUWzufx+0xrzBzb1Wqr1q1UCFSlYTBr7EEngU8MGbG6QHkZb+Q/1W7WOjvJKCyWXOdhrAsejnE2r/wZwmpZZSDjRyn2AhJ5esQRIzKY="
   
install:
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libboost-dev
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y libtbb-dev
     
before_script:
  - mkdir build
  - cd build
  - cmake ..

addons:
  coverity_scan:
    project:
      name: "ickby/openDCM"
      description: "Build submitted via Travis CI"
    notification_email: stefantroeger@gmx.net
    build_command:   "make"
    branch_pattern: master
    
script: make
