language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:apokluda/boost1.53 -y
  
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update

install:
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libboost1.53-dev
  - sudo apt-get install -y libtbb-dev
   
  # g++4.8.1 for c++11
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4 for c++11
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
