language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install -y libboost-system-dev
  - sudo apt-get install -y libboost-filesystem-dev
  - sudo apt-get install -y libtbb-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
